### ISSUE TITLE
Does not Run on Windows

### ISSUE THREAD

**Issue by LAPCODING123** [JLO64/Hardware-Donations-Desktop-App#1]
<img width="1248" alt="Hardware-Donations-App-Windows_Test-02" src="https://user-images.githubusercontent.com/43160245/77386420-f9d7da80-6d47-11ea-9499-773772875333.PNG">
I followed all the steps on the README., except for that part on installing system wide since it is for Linux. Tested in Windows Sandbox
5d5edbd4ac68a8850e746b92c8cfc513d0b1dc52

**Comment by JLO64** [comment]
The apparent issue here is how there is no region set for the AWS Boto3 API. On my computer this was not an issue since I already had the AWS CLI installed on my computer.

Just pushed the fix.

**Comment by LAPCODING123** [comment]
Now is able to run in 2cfec7247a6f0bcf47584aade024c1e1718eb069
