### ISSUE TITLE
Windows: Cannot sign into Database using Test Account

### ISSUE THREAD

**Issue by LAPCODING123** [JLO64/Hardware-Donations-Desktop-App#3]
<img width="1156" alt="Hardware-Donations-App-Windows_Test-04" src="https://user-images.githubusercontent.com/43160245/77483453-648b2380-6de5-11ea-8eab-673d937bb671.PNG">

2cfec7247a6f0bcf47584aade024c1e1718eb069

**Comment by JLO64** [comment]
The issue was a lack of credentials to access the AWS Lambda login function.  This was not an issue on my system because it already had credentials from the AWS CLI I had installed.
